### ISSUE TITLE
choix et implémentation de l'algorithme de maillage 3D

### ISSUE THREAD

**Issue by jguinet** [CS-SI/2018_ups_iarf-rodeco_schoolproject#10]

**Comment by AlexandreBerdeaux** [comment]
Pour l'algorithme de maillage nous avons décidé d'implémenter la méthode de salman. La méthode étant assez modulaire j'ai ouvert des issue pour les discussions des détails d'implémentation.

En pré-traitement
- #12 

Traitement
- #11 
- #13

**Comment by jguinet** [comment]
ce choix nous convient
