### ISSUE TITLE
[Salman] Generation des arêtes de contours et de la soupe de triangles

### ISSUE THREAD

**Issue by AlexandreBerdeaux** [CS-SI/2018_ups_iarf-rodeco_schoolproject#11]
Entrée : Nuage de point sous format netcdf, images de contours pour chaque vue

Il s'agit d'effectuer une première triangulation du nuage de point et de trier les côtés avec les image extraites en résultat de #12 pour ne garder que les côtés en correspondances avec des contours.
Les côtés ainsi obtenu seront utilisé comme contrainte pour une seconde triangulation.

**Comment by Houssem-25** [comment]
J'ai corrigé la triangulation les résultats sont assez bons il reste qu'à supprimer les arêtes entre les points qui ne sont pas sur le même bord.

**Comment by amiotc** [comment]
La visualisation des résultats semble en effet très satisfaisante. Bravo.
