### ISSUE TITLE
[Salman] netCDF Linking library

### ISSUE THREAD

**Issue by Houssem-25** [CS-SI/2018_ups_iarf-rodeco_schoolproject#19]
On trouve des problèmes avec la compilation de notre programme, en particulier avec le linking du netCDF. Idéalement, nous voulons créer une CMakeLists qui gère l'utilisation des bibliothèques: CGAL Opencv et Netcdf, mais pour le netCDF, il y a peu de documentation, surtout pour la partie compilation. Avez-vous des pistes pour la compilation?

**Comment by jguinet** [comment]
La façon la plus propre de procéder est d'utiliser un "find package", par exemple : [FindNetCDF.cmake](
https://github.com/Kitware/VTK/blob/master/CMake/FindNetCDF.cmake)

sinon il faut définir le chemin vers l'include netcdf.h, et la librairie : [how-do-i-add-a-library-path-in-cmake](https://stackoverflow.com/questions/28597351/how-do-i-add-a-library-path-in-cmake)
