### ISSUE TITLE
Travail effectué au jour du 11/01/19

### ISSUE THREAD

**Issue by AlexandreBerdeaux** [CS-SI/2018_ups_iarf-rodeco_schoolproject#7]
Travail effectué

NetCDF : 
Enregistrement des données de position et capteur.
Ajout des lignes de visée.
Modification des noms des variables pour correspondre à s2p.

Mesh : 
 Lecture des algorithmes implementer sous CGAL et PCL 
Sélection de 3 autres algorithm : Salman - PowerCrust et TV Prior for High-Quality Scalable Multi-View Stereo Reconstruction qui est basé sur SGM. 

Classification : 
Lecture des articles sur Github
Présélection de certains algorithmes en éliminant les méthodes uniquement testée sur des scènes.

Rendu de la prochaine release : 
Etat de l’art sur le mesh.
Revue des articles sur l’extraction de MNT.
S2P avec génération de NetCDF.

**Comment by jguinet** [comment]
concernant le CR sur les Mesh :+1: 

> 
> Mesh :
> Lecture des algorithmes implementer sous CGAL et PCL
> Sélection de 3 autres algorithm : Salman - PowerCrust et TV Prior for High-Quality Scalable Multi-View > Stereo Reconstruction qui est basé sur SGM.
> 

- le choix des 3 autres algorithmes me semble pertinent, En particulier l'article de Kuhn (TV prior).
- n'hésitez pas à vous focaliser sur les points durs/défauts de votre sélection d'algorithmes

Merci pour votre retour
